### ISSUE TITLE
What is a SDK method that is equivalent to DeleteTimeSeriesPointsByTimeRange?

### ISSUE THREAD

**Issue by mattfung** [AquaticInformatics/aquarius-sdk-net#128]
I am wondering if Aquarius SDK has a method that is equivalent to `DeleteTimeSeriesPointsByTimeRange`? 
If not, I am wondering what is the best practice for deleting certain data points on a time series?

I am hoping to use the SDK on Aquarius 19.4.171

**Comment by DougSchmidt-AI** [comment]
Sorry @mattfung, I only saw this issue by chance right now (my GitHub email filters got overwhelmed). You can also feel free to raise an API question in our Support portal (and my team would have nagged me right away to respond!) :)

If you haven't resolved this problem yet, the answer will depend on the type of time-series.

You can use the latest SDK (v20.2.2) with your AQTS 19.4 system.

## Basic time-series - Use the [PostTimeSeriesOverwriteAppend](https://github.com/AquaticInformatics/aquarius-sdk-net/blob/develop/src/Aquarius.Client/TimeSeries/Client/ServiceModels/Acquisition.cs#L302) request

Use the `PostTimeSeriesOverwriteAppend` request with no `Points` and set the `TimeRange` property to the time-range to be deleted.

## Reflected time-series - Use the [PostRefectedTimeSeries](https://github.com/AquaticInformatics/aquarius-sdk-net/blob/develop/src/Aquarius.Client/TimeSeries/Client/ServiceModels/Acquisition.cs#L171) request 

Use the `PostTimeSeriesOverwriteAppend` request with no `Points` and set the `TimeRange` property to the time-range to be deleted.

This wiki page has a small writeup on appending to reflected time-series, but the logic for a basic is the same, you just use a different request DTO.

https://github.com/AquaticInformatics/aquarius-sdk-net/wiki/Appending-points-to-a-reflected-time-series

## These operations only delete raw points, not corrected points

There are no APIs for deleting points from the corrected signal. You will need to use the Data Review Tool in the browser to achieve that.

## Derived time-series - Not possible

You'll also need to use DRT here too.

**Comment by mattfung** [comment]
@DougSchmidt-AI  thanks for the explanation, this helps. I can use the portal in the future.
