### ISSUE TITLE
Changes Information Question

### ISSUE THREAD

**Issue by tdenkler0002** [AquaticInformatics/aquarius-sdk-net#135]
Afternoon,
Sorry if this isn't the right place to post a question (I contacted support and they suggested posting here). I wanted to see if you guys had any suggestions for the best way to get the data we are looking for.

**Background Info**
We are currently trying to implement NG coming from 3.X so we have quite a bit of legacy code that needs to stick around.
Several of our codebases utilize `GetDataSetList` and the `DataSet` object that comes from 3.X, so we are pretty much trying to recreate that with the info from NG. 

**The Problem**
Originally we were thinking of still trying to acquire/recreate the `TotalSamples` (from 3.X `GetDataSetList`) with NG, however we realize that this isn't really available unless we chain calls together (resulting in a massive amount of data for some totals) and further doesn't seem to really fit how with how Aquarius pulls that data anymore. This led us to thinking about the bigger issue and what we actually use `TotalSamples` for... which is basically for auditing and tracking purposes. 

We built a ChangeDetection Microservice similar to the logic in the samples page ChangeMonitor tool. However, we are still lacking a clear path to know if a point has been Added/Appended/Deleted. We see that we can use the `GetCorrectionsList` to obtain some information, but it seems the details are lacking for us to identify what operation occurred (other than delete, but even then we still have to determine how many points were affected in the time range). Additionally, we looked at comparing the `GetTiemSeriesRawData` with the `GettimeSeriesCorrectedData` endpoints to see point differences, however this seems like a lot of overhead and not 100% reliable for us to drill down enough on the actual points and point number changed by the operation.

One last thing we checked was the Acquisition API that offers that `GetTimeSeriesAppendStatus` with the `NumberOfPointsAppended` and `NumberOfPointsDeleted` - however we don't really have that information in relation to the `ChangesSince` token. 

Do you have any guidance on the best way to accomplish a sort of audit trail with the API that we can leverage or is this something that is currently not supported and we should consider putting a  feature request in for? 

Thanks for your time!

**Comment by DougSchmidt-AI** [comment]
Hi Tiffany. Since I've address this question in our Support portal, I'm going to close this issue here, and we can continue the discussion in the Support portal.
