### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by edgarbelda** [AquaticInformatics/aquarius-sdk-net#96]
Hi @DougSchmidt-AI 

I have a method to get active rating models but when there is not a active rating curve it throws an exception, for that reason I used a try-catch (you can see below). The problem is with the log, I would prefer not to see these errors. Is it possible?

![image](https://user-images.githubusercontent.com/14314396/58114535-369ee680-7bf8-11e9-826f-e859820ee9eb.png)

```
                try
                {
                    expandRatingCurve = client.Publish.Get(new EffectiveRatingCurveServiceRequest() { RatingModelIdentifier = rating.Identifier });
                }
                catch (Exception e)
                {
                    //No active rating model
                    continue;
                }
```

Thanks!

Regards

**Comment by DougSchmidt-AI** [comment]
First, a side note on [exception handling with the SDK](https://github.com/AquaticInformatics/aquarius-sdk-net/wiki/Error-Handling):

I'd really recommend changing the wide `catch(Exception e)` to the more narrow `catch(WebServiceException e)`, so that other client-side programming errors won't accidentally get swallowed. Your current code is very light, of couse, but as code grows over time, this type of catching all exceptions is generally a bad idea, since it can mask real errors.

I'll answer your real question about error-message supression in my next comment.

**Comment by DougSchmidt-AI** [comment]
There isn't an obvious way to suppress these WebServiceException stack traces from the SDK.

I've also started to notice this pattern recently, and I'd like to have some way to suppress them too, but I have not had a chance to dig into the details yet.

The internal ServiceStack.Client JsonServiceClient class is [logging the exception here](https://github.com/ServiceStack/ServiceStack/blob/v4.5.12/src/ServiceStack.Client/ServiceClientBase.cs#L811), and that is a bit out of the SDK's control.

There are a few approaches which could be tried to remove these from your integration:

## Remove all the ServiceStack logging completely

The [SDK guidance for logging](https://github.com/AquaticInformatics/aquarius-sdk-net/wiki/Logging-error-responses) recommends registring a concrete logging provider with the ServiceStack.Logging.LogManager ILogFactory instance.

If your integration never sets `LogManager`, then your log won't get these messages.

The downside is that you also won't get other messages from the SDK or ServiceStack. There isn't much else that logs, so maybe this isn't as dramatic a change as it may appear.

## Change the log verbosity for the `ServiceStack.ServiceClientBase` class

This will depend on which concrete logger implementation your integration is using. I tend to use `log4net`, but you might be using another logging framework.

For log4net, you can follow [this guidance](https://stackoverflow.com/questions/13980615/how-do-i-configure-log4net-for-a-different-level-for-some-classes), and just tell log4net to only allow FATAL messages from this ServiceStack class to be logged.

```xml
<log4net>
  <!-- other config settings -->
  <root>
    <level value="INFO" />
    <appender-ref ref="ConsoleAppender" />
    <appender-ref ref="RollingFileAppender" />
  </root>
  <logger name="ServiceStack.ServiceClientBase">
    <level value="FATAL"/>
  </logger>
</log4net>

```

**Comment by edgarbelda** [comment]
### Solved!
I'm using also `log4net` I changed the log verbosity for the `ServiceStack.ServiceClientBase` class as you told me and now it works. Thank you very much.
![image](https://user-images.githubusercontent.com/14314396/58124572-d9625f80-7c0e-11e9-9dd5-0b28c6960b0f.png)
Thanks also for the exception handling with the SDK, it's interesting. I'll check for the rest of the code.

Regards,

**Comment by DougSchmidt-AI** [comment]
Glad to hear it worked. I'll close this issue then.
